### ISSUE TITLE
Yet another binding, and some issues

### ISSUE THREAD

**Issue by hadrielk** [rrthomas/lrexlib#6]
Hi,
This is more of a courtesy message than anything else - I'm not sure if you're still updating lrexlib these days or not. (?)

I write code for an open source tool called Wireshark (wireshark.org), and used lrexlib to expose yet another regex engine type: the Glib regex library, which is basically PCRE under the hood but with a Glib-specific API. I doubt anyone else would want/need such a thing, when they could just use the lrexlib PCRE binding as is; but I needed it because Wireshark gets built with Glib already, but not with PCRE directly, and I didn't want to add more complication to the build process/steps. (Wireshark is quite large and is fairly complicated to build already)  If you'd like the Glib binding anyway, let me know and I'll push the latest to my fork of lrexlib and send you a pull request.

But the reason I'm submitting this issue as an issue is we found several compilation errors and warnings when building lrexlib. Some of them are because we have to support Wireshark being built with various compilers on many platforms, and invariably one or another of those is stricter than others for certain C-standard rules.  If you'd like to fix those in your lrexlib repository, let me know and I'll push just those changes to a fork and send you a pull request. (i.e., separately from the Glib regex binding if you don't want that)

**Comment by Lekensteyn** [comment]
AFAICS this is a change that is worth applying now:
- [Use luaL_{check,opt}integer() rather than luaL_{check,opt}int().](https://code.wireshark.org/review/6744)

These sqelch some compiler warnings due to type mismatches:
- [Fix some compiler issues on windows with Lua 5.2](https://code.wireshark.org/review/860)
- [Fix lrexlib.c clang static analyzer warning](https://code.wireshark.org/review/661)
- [Add two more casts to satisfy OSX10.6 buildbot](https://code.wireshark.org/review/582)
- [add explicit casts to fix compilation on Linux](https://code.wireshark.org/review/577)

**Comment by rrthomas** [comment]
I suspect all of these bugs have been fixed (and unfortunately the links to Wireshark pages no longer work), so closing.

Certainly, `luaL_optinteger` is now used, and lrexlib works on Lua 5.2 (and later), and compiles without problems on current Linux.
